# Generated by Django 2.2.9 on 2023-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.RemoveField(
            model_name='data',
            name='group',
        ),
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
