# Generated by Django 2.2.9 on 2023-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20230315_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
