# Generated by Django 2.2.9 on 2023-03-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_data_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
